---
name: Install bazelisk

inputs:
  bazelisk-version:
    description: Bazelisk version
    required: false
    # Note that the default value below is managed by `.github/workflows/update-install-bazelisk.yml`
    default: "v1.23.0"

runs:
  using: composite
  steps:
    - name: Install bazelisk
      shell: bash
      run: |
        bazelisk_dir=$(realpath "$(mktemp -d bazelisk_dir.XXXXXXXXXX)")
        if [ "${RUNNER_OS}" == "Linux" ]; then
          bazelisk_basename="bazelisk-linux-amd64"
        elif [ "${RUNNER_OS}" == "macOS" ]; then
          bazelisk_basename="bazelisk-darwin-amd64"
        elif [ "${RUNNER_OS}" == "Windows" ]; then
          bazelisk_basename="bazelisk-windows-amd64.exe"
        else
          echo "${RUNNER_OS} not supported"
          exit 1
        fi

        curl -OL "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/${bazelisk_basename}" && \
          mv "${bazelisk_basename}" "${bazelisk_dir}/bazelisk"
        chmod +x "${bazelisk_dir}/bazelisk"
        echo "${bazelisk_dir}" >> "${GITHUB_PATH}"
      env:
        BAZELISK_VERSION: ${{ inputs.bazelisk-version }}
