---
name: Install bazelisk

inputs:
  bazelisk-version:
    description: Bazelisk version
    required: false
    # Note that the default value below is managed by `.github/workflows/update-install-bazelisk.yml`
    default: "v1.23.0"

runs:
  using: composite
  steps:
    - name: Make directory
      shell: bash
      id: mkdir
      run: |
        bindir="${RUNNER_TEMP}/yuyawk/github-actions/install-bazelisk"
        mkdir -p "${bindir}"
        echo "${bindir}" >> "${GITHUB_PATH}"
        echo "bindir=${bindir}" >> "${GITHUB_OUTPUT}"
    - name: Cache downloaded binary
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ steps.mkdir.outputs.bindir }}
        key: yuyawk/github-actions/install-bazelisk-${{ runner.os }}-${{ inputs.bazelisk-version }}
    - name: Install bazelisk if needed
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        if [ "${RUNNER_OS}" == "Linux" ]; then
          bazelisk_basename="bazelisk-linux-amd64"
        elif [ "${RUNNER_OS}" == "macOS" ]; then
          bazelisk_basename="bazelisk-darwin-amd64"
        elif [ "${RUNNER_OS}" == "Windows" ]; then
          bazelisk_basename="bazelisk-windows-amd64.exe"
        else
          echo "${RUNNER_OS} not supported"
          exit 1
        fi

        curl -OL "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/${bazelisk_basename}" && \
          mv "${bazelisk_basename}" "${BINDIR}/bazelisk"
        chmod +x "${BINDIR}/bazelisk"
      env:
        BAZELISK_VERSION: ${{ inputs.bazelisk-version }}
        BINDIR: ${{ steps.mkdir.outputs.bindir }}
