name: Update major version tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  update-major-version:
    name: Update major version tag
    runs-on: ubuntu-22.04
    steps:
      - name: Generate GitHub Apps token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.TAG_UPDATER_APP_ID }}
          private-key: ${{ secrets.TAG_UPDATER_APP_PRIVATE_KEY }}
      - uses: nowactions/update-majorver@v1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
